### PR TITLE
Add tutorial on moving to node pools

### PR DESCRIPTION
**Pull request by shrivara**
https://github.com/Shippable/pm/issues/9943

### CODE REVIEW

**Review by ambarish2012 — APPROVED** [review]
Looks good.

**Comment by manishas** [comment]
I don't know if this should be in docs....aren't these temporary instructions for folks on custom nodes?

**Comment by manishas** [comment]
also, this doesn't mention that they have to reinitialize their nodes after clicking on the upgrade button. Isn't that a necessary step?

**Comment by manishas** [comment]
on closer reading, it does say re-initialize. but we need to be very specific and give them step by step directions. I think these should be in an email we send to all custom hosts folks and not in a tutorial.

**Comment by ambarish2012** [comment]
I think we should document this as there will be people not reading their emails. This document can be removed once everyone is upgraded.

**Comment by manishas** [comment]
@ric03uec I specifically asked not to merge this. Please talk to me if you see my notes in the future.

**Pull request merged**
