### PR TITLE
update couchdb version in docs

### PR DESCRIPTION
**Pull request by bindushree16**
https://github.com/Shippable/pm/issues/10775

### CODE REVIEW

**Comment by ric03uec** [comment]
needs a screenshot of the docs page

**Comment by bindushree16** [comment]
image

**Comment by bindushree16** [comment]
image

**Comment by ric03uec** [comment]
did we start installing couchdb only in v6.2.4 release for ubuntu 16.04 aarch64? also, was couchdb not updated for aarch64 ubuntu 16.04 in the release v6.4.4?

**Comment by bindushree16** [comment]
yaa we start installing couchdb only in v6.2.4 release for ubuntu16.04 aarch64 and 2.1.1 version is not supported by aarch64 so we keep that version same

https://hub.docker.com/r/drydock/aarch64_u16all/tags/

**Pull request merged**
