### PR TITLE
adds docs for Jira issues and describes how to use Jira integration to create issues

### PR DESCRIPTION
**Pull request by Riturajcse**
https://github.com/Shippable/docs/issues/1031

image

---

image

---

image

---

image

---

image

---
image

### CODE REVIEW

**Comment by rageshkrishna** [comment]
We should have a screenshot that shows where the "Create issue" link will be present. It's not that easy to find.

We should clarify that "Subscription integration" will be presented in the modal only if there are multiple Jira integrations defined for the subscription.

The steps for both runCI and other jobs are the same, so why duplicate it? Can't we just describe it in a single section for both things?

**Comment by manishas** [comment]
I think this should be in platform->tutorials->integrations. Even though our backend implementation is similar to a notification service, the actual functionality doesn't have much to do with notifications... it's creating tickets. Nobody will think of finding JIRA issues in notifications section.... plus we haven't really implemented this with yml blocks like other notification providers.

**Comment by Riturajcse** [comment]
@manishas Moved creating Jira issues page to `platform -> tutorials -> integrations` as suggested by you.

**Comment by ambarish2012** [comment]
A few more comments:

1. Replace `jira`  and `JIRA` with `Jira` everywhere. Please do a detailed scan and change this everywhere.

2. Remove `### Shippable Utility Functions` section since there is no notification yml support.

3. `Creating JIRA issues` -> `Creating Jira issues`

4. `Before you start, you will need to connect your Jira account with Shippable so we have the credentials to create issues on your behalf. We do this through [Account Integrations](../platform/integration/overview/), so that any sensitive information is abstracted from your config file. Once you add an account integration, you can add it to different subscriptions for creating issues.
There are 2 steps to add a Jira integration: Generating an API token for Jira, , and adding the token to your Shippable account.`

-> 

`Before you start, you will need to specify your Jira account credentials in a [Jira account integration](/platform/integration/jira) so that Shippable can create tickets in your Jira server on your behalf. `


5. `There are 2 steps to add a Jira integration: Generating an API token for Jira, , and adding the token to your Shippable account`

->

`Steps to add a Jira integration`

6.  `###2. Add the Jira integration to your Account` -> `[Create a Jira Account Integration](link here to the Account integration)`.  

Remove the duplicated information below Step 2, linking is adequate.

7. `Once you have completed the Setup steps, you are ready to create issues for your Jira projects from Shippable UI. To enable any subscription to create Jira issues you should first create a Jira subscription integration for that subscription using the Jira account integration you have already added.`

->

`Once you have completed the Setup, you will need to create a subscription integration for the Jira account subscription .`

8. `Here in this modal you need to input all the required info` -> `In this moda,l you will need to input all the required information.`

9. ` If your subscription had multiple Jira subscription integrations, select the correct subscription integration having access to your Jira site. If your subscription has only one Jira subscription integration then by default this will be used for creating Jira issues.` -> `select the appropriate Jira subscription integration.`

10. `In the summary section give a brief summary about your issue` -> `In the summary section, give a brief summary about your issue

11. `In the description section add the description about your issue.` -> `In the description section, add the description about your issue.`

12. `In case of matrix jobs you can select if you want to attach `All` , `Unsuccessful` or `None` of the logs. For non-matrix job and runSh jobs you can select the checkbox if you want to attach console logs with your Jira issue. ` 

->

`For matrix runCI jobs, you can attach `All`, `Unsuccessful` or `None` of the logs. For non-matrix runCI and runSh jobs, you can select the checkbox if you want to attach console logs to your Jira ticket.`

13. `Now after filling all the details if you click on `Save` modal will go away and create issue link will get replaced by link of your new Jira issue, clicking this link will open you Jira issue in a new tab.` 

->

 `Click on `Save` after filling in all the fields. Thereafter, the `create issue` link will get replaced by a link to your Jira ticket created on your Jira server. Clicking this link will open the ticket in a new tab.`


14. 
`
* **Username** -- login to your jira server
* **Token** -- your token token with the permissions needed to access jira rest apis
`

-> 

`
* **Username** -- account username
* **Token** -- account token with permissions on the Jira rest apis
`

**Pull request merged**
