### PR TITLE
changes in Ruby

### PR DESCRIPTION
**Pull request by vijayreddy1991**
https://github.com/Shippable/pm/issues/10776

image

### CODE REVIEW

**Comment by ric03uec** [comment]
lets make different tables for ruby and jruby

**Comment by vijayreddy1991** [comment]
ok

**Comment by ric03uec** [comment]
fix formatting. the machine image column entries should not have any `-`as leading character

**Comment by vijayreddy1991** [comment]
ok

**Comment by ric03uec** [comment]
are the screenshots updated. i still see the `-` character for a lot of rows

**Comment by vijayreddy1991** [comment]
ok

**Comment by ric03uec** [comment]
why do we have so many screenshots in this? this should just have two. one for ruby and one for jruby

**Comment by vijayreddy1991** [comment]
ok, i will update only latest screenshot

**Pull request merged**
