### PR TITLE
 add docs for externalCI integration functionality

### PR DESCRIPTION
**Pull request by ankul-shippable**
#1009

### CODE REVIEW

**Comment by rageshkrishna** [comment]
@ankul-shippable IN steps on externalCI are not supported yet. We should not be showing that as a possibility here.

**Comment by ankul-shippable** [comment]
ok, removed

**Comment by ambarish2012** [comment]
1. Replace `external pipeline` with `your continuous integration jobs in other CI servers such as Jenkins`.

2. Replace `This job is used to integrate non-Shippable CI-CD platform jobs to Shippable.` with `This job is used to integrate any job in your existing CI server with your Shippable assembly line so that you can easily view all the job metadata such as job name, status code, start and stop timestamps in your Shippable dashboard`.

3. `page_title: gitRepo resource reference` -> should be `page_title: externalCIServer resource reference`

4.  `page_description: List of supported jobs` -> `page_description: How to  integrate any job in your existing CI server with your Shippable assembly line using Shippable API`.

5. Replace `You can create a externalCI job by [adding](/platform/tutorial/workflow/crud-job#adding) it to shippable.yml` -> `You can create a externalCI job by adding it to your shippable.yml file and thereafter [creating a syncRepo](/platform/tutorial/workflow/crud-job#adding) in your Shippable UI.`

**Comment by ambarish2012** [comment]
Looks good.

**Pull request merged**
