### PR TITLE
update all languages for v6.5.4

### PR DESCRIPTION
**Pull request by vijayreddy1991**
https://github.com/Shippable/pm/issues/10956

image
image
image
image
image

### CODE REVIEW

**Comment by ric03uec** [comment]
We don't support language:jruby this needs to be removed

**Comment by vijayreddy1991** [comment]
@ric03uec we do support  jruby on ubuntu14.04  https://rcapp.shippable.com/github/vijayreddy1991/jobs/u14ruball-test/builds/5b052108b44cea0700ad7aaf/console

**Comment by ric03uec** [comment]
I'm saying we don't support jruby tag

**Comment by vijayreddy1991** [comment]
ok

**Pull request merged**
