### PR TITLE
CLI Docs update

### PR DESCRIPTION
**Pull request by Ranjansingh41**
https://github.com/Shippable/pm/issues/1077

image

### CODE REVIEW

**Comment by ric03uec** [comment]
needs a screenshot of the docs

**Comment by Ranjansingh41** [comment]
image

**Comment by ric03uec** [comment]
1.11.91 is listed twice in this. any version can only be listed once.

**Comment by Ranjansingh41** [comment]
image

**Comment by ric03uec** [comment]
please follow the same order of listing os as we're doing in http://docs.shippable.com/platform/runtime/machine-image/os-versions/
- ubuntu 14.04 -> ubuntu 16.04 -> ubuntu 16.04 (aarch64) -> windows -> mac -> centos

**Comment by ric03uec** [comment]
the latest screenshot needs to be updated in the description

**Comment by Ranjansingh41** [comment]
image

**Comment by ric03uec** [comment]
please update the first comment with the screenshot. its easier for the reviewer to figure out whats the final update if the first comment always has the latest version

**Pull request merged**
